import json, hashlib
from pathlib import Path
# Original instructional vocabulary and activities, not copied textbook pages.
RAW = '''Pinyin và thanh điệu|Âm tiết gồm thanh mẫu, vận mẫu và thanh điệu. Thanh 1 cao ngang; thanh 2 đi lên; thanh 3 thấp rồi lên; thanh 4 đi xuống; thanh nhẹ ngắn. Nghe mẫu trước khi đọc, không đọc Pinyin như tiếng Việt.|妈,mā,mẹ;麻,má,cây gai;马,mǎ,ngựa;骂,mà,mắng;吗,ma,trợ từ hỏi;八,bā,tám;爸,bà,bố;你,nǐ,bạn;好,hǎo,tốt;我,wǒ,tôi;不,bù,không;是,shì,là|你好！|Nǐ hǎo!|Xin chào!
Chào hỏi|你好 là lời chào thông dụng. 你好吗？ là câu hỏi. Hai thanh 3 liền nhau: thanh 3 đầu thường đọc gần thanh 2, như 你好. Pinyin vẫn ghi thanh gốc.|您好,nín hǎo,xin chào lịch sự;早上,zǎoshang,buổi sáng;晚上,wǎnshang,buổi tối;再见,zàijiàn,tạm biệt;谢谢,xièxie,cảm ơn;不客气,bú kèqi,không có gì;对不起,duìbuqǐ,xin lỗi;没关系,méi guānxi,không sao;请,qǐng,mời / xin;您,nín,ngài / bạn lịch sự;很,hěn,rất;也,yě,cũng|你好！你好吗？我很好，谢谢！|Nǐ hǎo! Nǐ hǎo ma? Wǒ hěn hǎo, xièxie!|Xin chào! Bạn khỏe không? Tôi khỏe, cảm ơn!
Giới thiệu bản thân|我叫 + tên: Tôi tên là... 你叫什么名字？ hỏi tên. 什么 đặt tại vị trí thông tin cần hỏi. Thay tên trong mẫu bằng tên của bạn.|叫,jiào,tên là / gọi;名字,míngzi,tên;什么,shénme,cái gì;人,rén,người;中国,Zhōngguó,Trung Quốc;越南,Yuènán,Việt Nam;学生,xuésheng,học sinh;老师,lǎoshī,giáo viên;朋友,péngyou,bạn bè;认识,rènshi,quen biết;高兴,gāoxìng,vui;姓,xìng,họ|我叫路易。我是越南人。很高兴认识你。|Wǒ jiào Lùyì. Wǒ shì Yuènán rén. Hěn gāoxìng rènshi nǐ.|Tôi tên Louis. Tôi là người Việt Nam. Rất vui được biết bạn.
Số và tuổi|Số 11 là 十一, 20 là 二十, 21 là 二十一. 我今年...岁 nói tuổi. 几 thường hỏi số lượng nhỏ. 两 thường dùng trước lượng từ, như 两个人.|一,yī,một;二,èr,hai;三,sān,ba;四,sì,bốn;五,wǔ,năm;六,liù,sáu;七,qī,bảy;九,jiǔ,chín;十,shí,mười;岁,suì,tuổi;今年,jīnnián,năm nay;几,jǐ,mấy|你今年几岁？我今年四十一岁。|Nǐ jīnnián jǐ suì? Wǒ jīnnián sìshíyī suì.|Năm nay bạn bao nhiêu tuổi? Năm nay tôi 41 tuổi.
Gia đình|我的... là ... của tôi. 家有...: gia đình có... 个 là lượng từ thông dụng. Dùng 两个人 cho hai người. Có thể lược 的 trong 我的妈妈 thành 我妈妈.|妈妈,māma,mẹ;爸爸,bàba,bố;哥哥,gēge,anh trai;姐姐,jiějie,chị gái;弟弟,dìdi,em trai;妹妹,mèimei,em gái;儿子,érzi,con trai;女儿,nǚ'ér,con gái;家,jiā,nhà / gia đình;有,yǒu,có;个,gè,lượng từ chung;两,liǎng,hai trước lượng từ|我家有四个人。这是我妈妈。|Wǒ jiā yǒu sì ge rén. Zhè shì wǒ māma.|Nhà tôi có bốn người. Đây là mẹ tôi.
Ngày tháng|Thứ tự ngày: năm, tháng, ngày. 今天星期几？ hỏi thứ. 日期 dùng số đếm, không dùng số thứ tự. Đọc ngày sinh của chính mình.|今天,jīntiān,hôm nay;明天,míngtiān,ngày mai;昨天,zuótiān,hôm qua;年,nián,năm;月,yuè,tháng;号,hào,ngày trong tháng;星期,xīngqī,tuần / thứ;星期一,xīngqīyī,thứ hai;星期日,xīngqīrì,chủ nhật;生日,shēngrì,sinh nhật;时候,shíhou,lúc;哪,nǎ,nào|今天星期一。你的生日是几月几号？|Jīntiān xīngqīyī. Nǐ de shēngrì shì jǐ yuè jǐ hào?|Hôm nay thứ hai. Sinh nhật bạn là ngày mấy tháng mấy?
Giờ và lịch học|Thời gian thường đặt trước động từ: 我晚上学习中文. 三点半 là 3 giờ rưỡi. 每天 + hoạt động nói thói quen.|现在,xiànzài,bây giờ;点,diǎn,giờ;分,fēn,phút;半,bàn,nửa;上午,shàngwǔ,buổi sáng;下午,xiàwǔ,buổi chiều;中午,zhōngwǔ,buổi trưa;每天,měitiān,mỗi ngày;学习,xuéxí,học;中文,Zhōngwén,tiếng Trung;时间,shíjiān,thời gian;开始,kāishǐ,bắt đầu|我每天学习三十分钟中文。现在八点半。|Wǒ měitiān xuéxí sānshí fēnzhōng Zhōngwén. Xiànzài bā diǎn bàn.|Tôi học tiếng Trung 30 phút mỗi ngày. Bây giờ là 8 giờ rưỡi.
Ăn uống|我想吃... diễn đạt muốn ăn. 不 đọc bú trước thanh 4: 不是 bú shì. 一 đổi thanh trong lời nói tùy âm sau, Pinyin cơ bản vẫn có thể ghi yī.|吃,chī,ăn;喝,hē,uống;水,shuǐ,nước;茶,chá,trà;咖啡,kāfēi,cà phê;米饭,mǐfàn,cơm;面条,miàntiáo,mì;菜,cài,món ăn / rau;水果,shuǐguǒ,trái cây;苹果,píngguǒ,táo;想,xiǎng,muốn / nghĩ;杯,bēi,cốc|我想喝一杯茶，吃一点儿米饭。|Wǒ xiǎng hē yī bēi chá, chī yīdiǎnr mǐfàn.|Tôi muốn uống một cốc trà, ăn một ít cơm.
Gọi món|请给我...: xin cho tôi... 要 có thể diễn đạt muốn lấy. ...多少钱？ hỏi giá. Không thêm 吗 vào câu đã có từ hỏi như 什么、多少.|菜单,càidān,thực đơn;饭店,fàndiàn,nhà hàng;服务员,fúwùyuán,nhân viên phục vụ;要,yào,muốn lấy / cần;给,gěi,cho;鸡肉,jīròu,thịt gà;牛肉,niúròu,thịt bò;鱼,yú,cá;鸡蛋,jīdàn,trứng gà;好吃,hǎochī,ngon;一点儿,yīdiǎnr,một ít;买单,mǎidān,thanh toán bữa ăn|服务员，请给我菜单。我想要面条。|Fúwùyuán, qǐng gěi wǒ càidān. Wǒ xiǎng yào miàntiáo.|Bạn phục vụ, xin cho tôi thực đơn. Tôi muốn gọi mì.
Mua sắm và giá|这... là ... này; 那... là ... kia. 块 dùng nói tiền tệ trong hội thoại. 太...了: quá... Không phải mọi 了 đều chỉ quá khứ.|买,mǎi,mua;卖,mài,bán;钱,qián,tiền;多少,duōshao,bao nhiêu;块,kuài,đồng / miếng;这,zhè,này;那,nà,kia;贵,guì,đắt;便宜,piányi,rẻ;太,tài,quá;商店,shāngdiàn,cửa hàng;东西,dōngxi,đồ vật|这个多少钱？太贵了！便宜一点儿吧。|Zhège duōshao qián? Tài guì le! Piányi yīdiǎnr ba.|Cái này bao nhiêu tiền? Đắt quá! Rẻ hơn một chút nhé.
Vị trí và chỉ đường|在 + địa điểm: ở... 哪里 hỏi ở đâu. Danh từ + 左边/右边 diễn đạt vị trí. 请问 mở đầu câu hỏi lịch sự.|在,zài,ở / đang;哪里,nǎlǐ,ở đâu;这里,zhèlǐ,ở đây;那里,nàlǐ,ở kia;左边,zuǒbian,bên trái;右边,yòubian,bên phải;前面,qiánmiàn,phía trước;后面,hòumiàn,phía sau;里面,lǐmiàn,bên trong;外面,wàimiàn,bên ngoài;旁边,pángbiān,bên cạnh;请问,qǐngwèn,xin hỏi|请问，商店在哪里？在饭店旁边。|Qǐngwèn, shāngdiàn zài nǎlǐ? Zài fàndiàn pángbiān.|Xin hỏi, cửa hàng ở đâu? Ở cạnh nhà hàng.
Đi lại|去 + địa điểm: đi đến... 坐 + phương tiện: đi bằng... 怎么去？ hỏi cách đi. 从 A 到 B: từ A đến B.|去,qù,đi;来,lái,đến;回,huí,trở về;坐,zuò,ngồi / đi xe;车,chē,xe;出租车,chūzūchē,taxi;公交车,gōngjiāochē,xe buýt;地铁,dìtiě,tàu điện ngầm;机场,jīchǎng,sân bay;怎么,zěnme,thế nào;到,dào,đến;从,cóng,từ|从这里到机场怎么去？我坐出租车去。|Cóng zhèlǐ dào jīchǎng zěnme qù? Wǒ zuò chūzūchē qù.|Từ đây đến sân bay đi thế nào? Tôi đi taxi.
Sinh hoạt hằng ngày|Cấu trúc thời gian + hành động giúp kể lịch ngày. 先...再... là trước... rồi... Dùng mẫu đơn giản rồi thêm giờ cụ thể.|起床,qǐchuáng,thức dậy;睡觉,shuìjiào,ngủ;上班,shàngbān,đi làm;下班,xiàbān,tan làm;工作,gōngzuò,công việc / làm việc;休息,xiūxi,nghỉ ngơi;洗,xǐ,rửa;看,kàn,xem / đọc;听,tīng,nghe;读,dú,đọc;写,xiě,viết;做,zuò,làm|我早上六点起床，晚上十点睡觉。|Wǒ zǎoshang liù diǎn qǐchuáng, wǎnshang shí diǎn shuìjiào.|Tôi dậy lúc 6 giờ sáng, ngủ lúc 10 giờ tối.
Công việc và học tập|会 + động từ chỉ kỹ năng đã học. 能 thường nói khả năng do điều kiện. 一点儿 dùng nói biết một chút. 我不会... không biết làm...|公司,gōngsī,công ty;同事,tóngshì,đồng nghiệp;学校,xuéxiào,trường học;电脑,diànnǎo,máy tính;手机,shǒujī,điện thoại;会,huì,biết làm;能,néng,có thể;说,shuō,nói;汉语,Hànyǔ,tiếng Hán;问题,wèntí,câu hỏi / vấn đề;明白,míngbai,hiểu;帮助,bāngzhù,giúp đỡ|我在公司工作。我会说一点儿汉语。|Wǒ zài gōngsī gōngzuò. Wǒ huì shuō yīdiǎnr Hànyǔ.|Tôi làm việc ở công ty. Tôi biết nói một chút tiếng Trung.
Sở thích|喜欢 + danh từ hoặc động từ: thích... 不喜欢 là không thích. 和 nối các danh từ; không dùng để nối mọi mệnh đề như tiếng Việt.|喜欢,xǐhuan,thích;爱,ài,yêu;运动,yùndòng,vận động;跑步,pǎobù,chạy bộ;游泳,yóuyǒng,bơi;足球,zúqiú,bóng đá;音乐,yīnyuè,âm nhạc;电影,diànyǐng,phim;书,shū,sách;钓鱼,diàoyú,câu cá;和,hé,và;一起,yīqǐ,cùng nhau|我喜欢钓鱼，也喜欢看电影。|Wǒ xǐhuan diàoyú, yě xǐhuan kàn diànyǐng.|Tôi thích câu cá, cũng thích xem phim.
Thời tiết|今天很热 nói thời tiết hôm nay. Trong câu tính từ, 很 thường giúp câu tự nhiên, không luôn mang nghĩa rất mạnh. 会 có thể chỉ khả năng xảy ra.|天气,tiānqì,thời tiết;热,rè,nóng;冷,lěng,lạnh;下雨,xiàyǔ,mưa;下雪,xiàxuě,tuyết rơi;晴天,qíngtiān,trời nắng;风,fēng,gió;夏天,xiàtiān,mùa hè;冬天,dōngtiān,mùa đông;暖和,nuǎnhuo,ấm;凉快,liángkuai,mát;怎么样,zěnmeyàng,thế nào|今天天气怎么样？很热，明天会下雨。|Jīntiān tiānqì zěnmeyàng? Hěn rè, míngtiān huì xiàyǔ.|Hôm nay thời tiết thế nào? Nóng, ngày mai có thể mưa.
Sức khỏe|我...不舒服 nói cảm giác khó chịu. ...疼 là đau... 需要 + danh từ/động từ nói nhu cầu. Luyện ngôn ngữ, không dùng bài này để tự chẩn đoán.|身体,shēntǐ,cơ thể;头,tóu,đầu;眼睛,yǎnjing,mắt;手,shǒu,tay;肚子,dùzi,bụng;疼,téng,đau;不舒服,bù shūfu,khó chịu;医生,yīshēng,bác sĩ;医院,yīyuàn,bệnh viện;药,yào,thuốc;生病,shēngbìng,bị bệnh;需要,xūyào,cần|我今天不舒服，头疼。我需要休息。|Wǒ jīntiān bù shūfu, tóu téng. Wǒ xūyào xiūxi.|Hôm nay tôi không khỏe, đau đầu. Tôi cần nghỉ.
Nhà ở và đồ vật|Số + lượng từ + danh từ: 一本书、一张桌子. 有 chỉ tồn tại/sở hữu; 在 chỉ vị trí. 桌子上有一本书: có một cuốn sách trên bàn.|房间,fángjiān,phòng;桌子,zhuōzi,bàn;椅子,yǐzi,ghế;床,chuáng,giường;门,mén,cửa;窗户,chuānghu,cửa sổ;灯,dēng,đèn;本,běn,lượng từ sách;张,zhāng,lượng từ vật phẳng;上,shàng,trên;下,xià,dưới;干净,gānjìng,sạch|桌子上有一本书。我的房间很干净。|Zhuōzi shàng yǒu yī běn shū. Wǒ de fángjiān hěn gānjìng.|Trên bàn có một cuốn sách. Phòng tôi rất sạch.
Màu sắc và quần áo|Tính từ + 的 + danh từ, như 红色的衣服. 穿 nói mặc quần áo; 戴 dùng phụ kiện. 件 là lượng từ thường gặp cho áo.|衣服,yīfu,quần áo;裤子,kùzi,quần;鞋,xié,giày;红色,hóngsè,màu đỏ;白色,báisè,màu trắng;黑色,hēisè,màu đen;蓝色,lánsè,màu xanh lam;大,dà,to;小,xiǎo,nhỏ;穿,chuān,mặc;件,jiàn,lượng từ áo / việc;新,xīn,mới|我想买一件蓝色的衣服。这件太大了。|Wǒ xiǎng mǎi yī jiàn lánsè de yīfu. Zhè jiàn tài dà le.|Tôi muốn mua một chiếc áo màu xanh lam. Chiếc này quá to.
Hẹn gặp và lời mời|我们一起...吧 là lời đề nghị. 可以吗？ hỏi có được không. 有空 không phải có chỗ trống, mà là có thời gian rảnh.|我们,wǒmen,chúng tôi / chúng ta;你们,nǐmen,các bạn;他们,tāmen,họ;有空,yǒu kòng,rảnh;忙,máng,bận;见面,jiànmiàn,gặp mặt;等,děng,đợi;可以,kěyǐ,có thể / được phép;吧,ba,trợ từ đề nghị;打电话,dǎ diànhuà,gọi điện;周末,zhōumò,cuối tuần;时候,shíhou,lúc|你周末有空吗？我们一起吃饭吧。|Nǐ zhōumò yǒu kòng ma? Wǒmen yīqǐ chīfàn ba.|Cuối tuần bạn rảnh không? Chúng ta cùng ăn cơm nhé.
Du lịch và khách sạn|想 + động từ diễn đạt mong muốn. 住 + khoảng thời gian: ở bao lâu. 请帮我... xin giúp tôi... 几天 hỏi mấy ngày.|旅游,lǚyóu,du lịch;酒店,jiǔdiàn,khách sạn;住,zhù,ở;护照,hùzhào,hộ chiếu;票,piào,vé;飞机,fēijī,máy bay;火车,huǒchē,tàu hỏa;行李,xíngli,hành lý;天,tiān,ngày;找,zhǎo,tìm;预订,yùdìng,đặt trước;房子,fángzi,nhà|我想预订一个房间，住两天。|Wǒ xiǎng yùdìng yī ge fángjiān, zhù liǎng tiān.|Tôi muốn đặt trước một phòng, ở hai ngày.
Việc đã làm|Động từ + 了 có thể chỉ sự hoàn thành; không tự động tương đương mọi thì quá khứ. 没有 + động từ phủ định việc đã xảy ra, thường bỏ 了.|了,le,trợ từ hoàn thành / thay đổi;没,méi,chưa / không đã;已经,yǐjīng,đã;昨天晚上,zuótiān wǎnshang,tối hôm qua;早饭,zǎofàn,bữa sáng;午饭,wǔfàn,bữa trưa;晚饭,wǎnfàn,bữa tối;以后,yǐhòu,sau này / sau khi;以前,yǐqián,trước đây;回来,huílái,trở về đây;看见,kànjiàn,nhìn thấy;完,wán,xong|我已经吃了晚饭。昨天我没去公司。|Wǒ yǐjīng chī le wǎnfàn. Zuótiān wǒ méi qù gōngsī.|Tôi đã ăn tối. Hôm qua tôi không đến công ty.
Kế hoạch và mong muốn|打算 + động từ là dự định. 因为...所以...: bởi vì...nên... Đặt thời gian trước hành động và chọn một kế hoạch thật để kể.|打算,dǎsuàn,dự định;希望,xīwàng,hy vọng;准备,zhǔnbèi,chuẩn bị;下星期,xià xīngqī,tuần sau;明年,míngnián,năm sau;再,zài,lại trong tương lai;先,xiān,trước;然后,ránhòu,sau đó;因为,yīnwèi,bởi vì;所以,suǒyǐ,vì vậy;但是,dànshì,nhưng;为什么,wèishénme,tại sao|我打算下星期去旅游，所以现在准备行李。|Wǒ dǎsuàn xià xīngqī qù lǚyóu, suǒyǐ xiànzài zhǔnbèi xíngli.|Tôi dự định đi du lịch tuần sau nên giờ chuẩn bị hành lý.
So sánh và mô tả|A 比 B + tính từ: A ... hơn B. 不要 đặt 很 trước tính từ trong mẫu so sánh đơn giản. 有一点儿... hơi... thường dùng với nhận xét không mong muốn.|比,bǐ,hơn trong so sánh;高,gāo,cao;矮,ǎi,thấp;长,cháng,dài;短,duǎn,ngắn;快,kuài,nhanh;慢,màn,chậm;多,duō,nhiều;少,shǎo,ít;远,yuǎn,xa;近,jìn,gần;有一点儿,yǒu yīdiǎnr,hơi|这家商店比那家近。这件衣服有一点儿贵。|Zhè jiā shāngdiàn bǐ nà jiā jìn. Zhè jiàn yīfu yǒu yīdiǎnr guì.|Cửa hàng này gần hơn cửa hàng kia. Áo này hơi đắt.
Hội thoại xử lý tình huống|听不懂 là nghe không hiểu; 请再说一遍 xin nói lại một lần. 慢一点儿 chậm hơn chút. Đặt câu hỏi khi chưa hiểu, thay vì chỉ nói 是.|听不懂,tīng bu dǒng,nghe không hiểu;再说一遍,zài shuō yī biàn,nói lại một lần;慢一点儿,màn yīdiǎnr,chậm hơn một chút;意思,yìsi,ý nghĩa;怎么说,zěnme shuō,nói thế nào;对,duì,đúng;错,cuò,sai;知道,zhīdào,biết;忘记,wàngjì,quên;记得,jìde,nhớ;没问题,méi wèntí,không vấn đề;请帮我,qǐng bāng wǒ,xin giúp tôi|对不起，我听不懂。请再说一遍，慢一点儿。|Duìbuqǐ, wǒ tīng bu dǒng. Qǐng zài shuō yī biàn, màn yīdiǎnr.|Xin lỗi, tôi nghe không hiểu. Xin nói lại một lần, chậm hơn chút.
Tổng ôn và tự giới thiệu|Ghép lời chào, tên, quốc tịch, công việc, gia đình, sở thích và kế hoạch thành đoạn 60–90 giây. Kiểm tra tích lũy dùng từ tất cả các tuần, không chỉ tuần cuối.|介绍,jièshào,giới thiệu;自己,zìjǐ,bản thân;练习,liànxí,luyện tập;复习,fùxí,ôn tập;考试,kǎoshì,kiểm tra;进步,jìnbù,tiến bộ;继续,jìxù,tiếp tục;努力,nǔlì,cố gắng;每天晚上,měitiān wǎnshang,mỗi tối;有意思,yǒu yìsi,thú vị;容易,róngyì,dễ;难,nán,khó|我每天学习中文。我喜欢学习，也喜欢钓鱼。我会继续努力。|Wǒ měitiān xuéxí Zhōngwén. Wǒ xǐhuan xuéxí, yě xǐhuan diàoyú. Wǒ huì jìxù nǔlì.|Tôi học tiếng Trung mỗi ngày. Tôi thích học và thích câu cá. Tôi sẽ tiếp tục cố gắng.'''
def aid(s): return hashlib.sha256(s.encode()).hexdigest()[:16]
weeks=[]
for row in RAW.splitlines():
    title,note,words,han,py,vi=row.split('|')
    vocab=[]
    for word in words.split(';'):
        h,p,v=word.split(','); vocab.append(dict(h=h,p=p,v=v,a=aid(h)))
    weeks.append(dict(title=title,note=note,words=vocab,sentence=dict(h=han,p=py,v=vi,a=aid(han))))
phases=['Từ mới và phát âm','Nghe và phân biệt âm','Từ mới và mẫu câu','Nghe rồi trả lời','Đọc và luyện viết','Hội thoại và ghi âm','Ôn tập và kiểm tra']
tasks=[
['Ôn 3 từ cũ (tuần đầu: nghe 4 thanh).','Học 6 từ đầu; nghe mỗi từ 3 lần.','Nghe mẫu câu, nhìn Pinyin rồi nhắc lại.','Tự nói 3 câu với từ mới, ghi âm.','Viết 2 chữ, quan sát thành phần chữ.'],
['Che nghĩa, nhớ lại 6 từ đã học.','Đọc hướng dẫn tuần và đối chiếu Pinyin.','Làm bài nghe: nghe trước khi xem đáp án.','Ghi âm 6 từ, nghe lại và so với mẫu.','Viết 2 chữ và đọc thành tiếng.'],
['Nhớ lại 6 từ đầu không nhìn nghĩa.','Học 6 từ còn lại, ghép với từ đã biết.','Nghe mẫu câu 3 lần, nhắc theo từng cụm.','Thay 2 thông tin trong mẫu bằng thông tin của mình.','Viết 2 chữ mới, tự đọc Pinyin.'],
['Ôn đủ 12 từ của tuần.','Đọc mẫu câu và hiểu vị trí từ hỏi.','Nghe không nhìn chữ, nói lại điều hiểu được.','Đặt và trả lời 3 câu hỏi dựa trên chủ đề.','Gõ hoặc viết câu trả lời ngắn.'],
['Đọc 12 chữ/từ và thử nhớ nghĩa.','Đọc mẫu câu, che Pinyin rồi đọc lại.','Nghe và kiểm tra cách đọc của mình.','Tự kể 3–5 câu về chủ đề tuần.','Luyện viết 2 chữ trên màn hình; tự so hình chữ.'],
['Ôn từ còn khó và điểm kiểm tra cũ.','Soạn hội thoại 4–6 lượt dùng mẫu tuần.','Nghe mẫu và nhắc lại theo nhịp.','Ghi âm hội thoại; nghe lại, tự sửa 1 lỗi.','Viết 1 câu từ hội thoại.'],
['Ôn từ sai của tuần.','Làm kiểm tra đọc và nghe, xem giải thích.','Nghe lại các mục trả lời sai.','Nói không nhìn mẫu 30–60 giây; tự đánh giá.','Viết 2 chữ và đánh dấu hoàn thành.']]
days=[dict(day=w*7+d+1,week=w,phase=d,title=phases[d]) for w in range(26) for d in range(7)]
root=Path(__file__).parent
(root/'app/src/main/assets/course.json').write_text(json.dumps(dict(weeks=weeks,days=days,tasks=tasks),ensure_ascii=False,indent=2))
assert len(weeks)==26 and len(days)==182
assert all(len(w['words'])==12 for w in weeks)
print('Validated:',len(days),'days,',len({x['h'] for w in weeks for x in w['words']}),'unique words/phrases')
